### ISSUE TITLE
What are the proper cvars for hosting a server?

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/pt6_bot_warfare#10]
I got my server working with bot warfare, and in the dedicated.cfg i have these cvars set

set bots_skill "7"
set bots_loadout_allow_op "true"
set bots_loadout_rank "0"
set bots_loadout_prestige "-2"
set bots_play_nade "1"
set bots_play_take_carepackages "1"
set bots_play_jumpdrop "1"
set bots_play_target_other "1"
set bots_play_killstreak "1"

How ever most of them dont work, the bots do not jump or drop shot, they are not difficult at all in the slightest even though i set them on the highest difficulty and they do not use op weapons. I've tried it with "1" or "0" or "true" but it didnt make a difference. Can i get the proper cvars? Because these ones are not working that i described

**Comment by ineedbots** [comment]
![image](https://user-images.githubusercontent.com/751729/165185023-d41a1ea3-e59a-4700-9259-a8c6eb99d3b4.png)

bots_skill can be 0, 1, 2 or 3 only

**Comment by ineedbots** [comment]
There is a lot less dvars because the bot logic for the most part is implemented in the engine code.

**Comment by whatcorey** [comment]
Is there a way to give them random guns and classes



-------- Original message --------
From: INeedGames ***@***.***>
Date: 4/25/22 3:29 PM (GMT-08:00)
To: ineedbots/pt6_bot_warfare ***@***.***>
Cc: whatcorey ***@***.***>, Author ***@***.***>
Subject: Re: [ineedbots/pt6_bot_warfare] What are the proper cvars for hosting a server? (Issue #10)


There is a lot less dvars because the bot logic for the most part is implemented in the engine code.
