### ISSUE TITLE
Changing bot difficulty cvar has no effect on dedicated servers

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/pt6_bot_warfare#12]
I have my own dedicated server, all the other cvars work fine, but ive tried bot_skill 3 and bot_difficulty 3, and none of them have any effect on the bots, they are still dumb and have no reaction time, its like they are on recruit[

**Comment by GaryTheNoTrashCougar** [comment]
Works on mine, I use `set bots_skill 3`

**Comment by LevelChecker** [comment]
> I have my own dedicated server, all the other cvars work fine, but ive tried bot_skill 3 and bot_difficulty 3, and none of them have any effect on the bots, they are still dumb and have no reaction time, its like they are on recruit[

You ever fix this? im having the same problem

**Comment by ineedbots** [comment]
https://github.com/ineedbots/pt6_bot_warfare/blob/master/raw/scripts/mp/botwarfare.gsc#L143

the dvar is `bots_skill`

**Comment by LevelChecker** [comment]
I see what the issue was, I was trying to set it to 0 so it can randomize bots difficulty but I dont think 0 randomizes in BO2, tried seeing it to like 4-5 as well and nothing changed bc I felt 3 was slightly too easy but it seems like 3 is the highest BO2 can go vs the other COD's
