### ISSUE TITLE
How exactly do I install and use this?

### ISSUE THREAD

**Issue by FisticuffsMcGee** [ineedbots/pt6_bot_warfare#14]
I've used some of your other bot mods for the other CoD games before and had few issues, but it seems that this one works differently from most of the others. I'm basically tech illiterate so I rely on the readme which it seems this one doesn't have. Help appreciated!

**Comment by serva12** [comment]
did you figure this out?

**Comment by FisticuffsMcGee** [comment]
I gave up some time ago lol. If you know and can tell me, that would be appreciated

**Comment by serva12** [comment]
managed to get it installed but cant figure out how to get the bots in the game haha

**Comment by ineedbots** [comment]
Instructions were added today
