### ISSUE TITLE
commands ???

### ISSUE THREAD

**Issue by Syncenergy20** [ineedbots/pt6_bot_warfare#21]
what do i need to do ? 
there is nothing new im confused ?
how to launch ??

**Comment by ineedbots** [comment]
readme should have what you are looking for

**Comment by Syncenergy20** [comment]
no its not, the readme got this in it 

Make sure that [PlutoniumT6](https://plutonium.pw/docs/install/) is installed, updated and working properly.
Download [this repository](https://github.com/ineedbots/pt6_bot_warfare/archive/refs/heads/master.zip).
Open the Bot Warfare archive you downloaded, open the folder you find inside and finally open the raw folder.
Extract/move the folders found inside the raw folder in %localappdata%\Plutonium\storage\t6
The mod is now installed, now run your game.
The mod should be loaded! Now go start a map and play!
