### ISSUE TITLE
please help me dont just close this ....

### ISSUE THREAD

**Issue by Syncenergy20** [ineedbots/pt6_bot_warfare#24]
1:i made the piw5 mod to work. only thing i cant find the dvar to edit setting.

2:the pt6 version  of the mod just dont work by doing this:
 Make sure that [PlutoniumT6](https://plutonium.pw/docs/install/) is installed, updated and working properly.
Download [this repository](https://github.com/ineedbots/pt6_bot_warfare/archive/refs/heads/master.zip).
Open the Bot Warfare archive you downloaded, open the folder you find inside and finally open the raw folder.
Extract/move the folders found inside the raw folder in %localappdata%\Plutonium\storage\t6
The mod is now installed, now run your game.
The mod should be loaded! Now go start a map and play!

but public game just show class and scorestreak ,private match wont work either unlike mw3 when hitting n nothing happen (in pt6)

**Comment by ineedbots** [comment]
You are supposed to use dvars to manage the bots (`bots_manage_add`)  #17 wants to add an in-game menu.
