### ISSUE TITLE
i got a new error i have never seen before?!

### ISSUE THREAD

**Issue by theminecraften66** [ineedbots/pt6_bot_warfare#26]
i was trying to play bot wafare in custom game and chose nuketown domination with no bots selected since i figured i could use the ingame menu when i spawn, so i start the match and midway through loading i get theis error?

****1 Script error(s):****Unresolved external:"botclearoverrides" with 0 parameters in "botwarfare" at line1****

**Comment by ScidaJ** [comment]
https://github.com/ineedbots/pt6_bot_warfare/issues/27

**Comment by ineedbots** [comment]
please use the latest gscs with the latest plutonium client
