### ISSUE TITLE
Removal of Dummy Override Classes in botwarfare.gsc Causing Server Crashes

### ISSUE THREAD

**Issue by ScidaJ** [ineedbots/pt6_bot_warfare#27]
The removal of these [lines](https://github.com/ineedbots/pt6_bot_warfare/commit/9c1a4451989053e749a94769225029976c83ee11#diff-9f884a7e6c5e51e53c4b7daaacc450302d90e5a37249159ac862ab36904542e1L684) seems to be the cause of this new bug. 

![image](https://github.com/ineedbots/pt6_bot_warfare/assets/22257604/93ea339a-ebf4-490d-a2d6-0a285eba2d79)

If these are true external classes then they are not implemented correctly.

**Comment by ScidaJ** [comment]
Adding them back then recompiling fixed the issue on my machine

**Comment by ineedbots** [comment]
please make sure you have the latest GSC files and have the latest Plutonium update 
![image](https://github.com/ineedbots/pt6_bot_warfare/assets/751729/aafc8a46-76b3-4c50-8967-baf79cf21637)

**Comment by ScidaJ** [comment]
I have the latest version of both. Stop closing issues that aren't resolved.
