### ISSUE TITLE
do you need to use server browser or not!?

### ISSUE THREAD

**Issue by theminecraften66** [ineedbots/pt6_bot_warfare#29]
just wondering if you need to start your own server to use the mod or not.

**Comment by Resxt** [comment]
@theminecraften66 no

**Comment by theminecraften66** [comment]
k does it have a menu or is there a special way of spawning bots like do i need to use the command bar or something cause i have tried in custom games and it gives me this error ****1 Script error(s):Unresolved external:"botclearoverrides" with 0 parameters in "botwarfare" at line1       and i am really confused cause i have the latest build downloaded from here on github

**Comment by Resxt** [comment]
An error is a file or code error. It's not related to you not typing commands in the console. This error means you still have old Bot Warfare files installed. Get a clean t6 storage and install Bot Warfare again.

Also yes you need to tweak dvars to make use of BW.
For example change the value of the `bots_manage_fill` dvar

**Comment by theminecraften66** [comment]
thank you for letting me know i need to change the dvars i did not know that. ill redownload bo2 and see if that works also do i delete my storage files inside of bo2 plutonium or just reinstall bo2 without tampering bo2 plutonium files

**Comment by theminecraften66** [comment]
one last thing what do i change the bots_manage_fill too

**Comment by theminecraften66** [comment]
meant to say where do i change the dvars is it also in storage

**Comment by Resxt** [comment]
It depends if it's for a server or a custom game.
Your game's console or the server's CFG is where you need to it.

**Comment by theminecraften66** [comment]
ok i am most likely going to be playing in custom match since i have tried to set up a server three separate times and just am not willing to go thru that

**Comment by theminecraften66** [comment]
so if i was to change it in the game console would i do it at the main menu or wait until i get into a lobby for custom match

**Comment by Resxt** [comment]
@theminecraften66 doesn't matter, it only changes when bots spawn
You can also paste this in a gsc file in the correct location to have it set to 12 automatically
```c
Init()
{
     SetDvar("bots_manage_fill", 12);
}
```

**Comment by DabtheGreat** [comment]
Okay i'm a bit dumb so i also need help, i downloaded the mod and did the installation but it seems it just doesn't work for me? I'm unsure what i did wrong, i downloaded it for the first time so i'm really new to this
