### ISSUE TITLE
Mod works and everything, but you don't earn any xp in custom games

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/pt6_bot_warfare#3]
For some reason you don't get any xp in custom games, so it would be impossible to rank up with friends because the only way you can play is custom games. Idk if there is a fix or not, hope to see this fixed

**Comment by ineedbots** [comment]
this is plutonium client related, not the mod


to rank up, go into a playlist public lobby, type `xpartygo` into the console to start the match, and use `bots_manage_add <int>` to add bots once in-game
