### ISSUE TITLE
Setting maximum bot difficulty with latest release

### ISSUE THREAD

**Issue by Ston3Cold** [ineedbots/pt6_bot_warfare#33]
Hi ineedbots,

I really love this project of yours, not to mention the fact that you're adding support for CoD 2 as well is nothing short of brilliant.

Just a quick question regarding T6's bot difficulty- I see in the code that the "bots_skill" setting makes use of the "bot_difficulty" dvar. Should one first set the bots' difficulty with the bot_difficulty dvar for bots_skill to interpret it correctly?

Because if I type "bots_skill", it doesn't indicate any default value. I love playing against the hardest bot skill available, but it seems that I just can't set the T6 bot warfare bots' skill to the maximum value that is supported.

Any feedback regarding how I can achieve this will be appreciated.

Thanks a lot,
SC

**Comment by ineedbots** [comment]
bots_skill is immediately cleared when it's set, but the value is copied into bot_difficulty, which is the dvar that's used for setting the difficulty

you can use either to set the difficulty, 0 is easiest and 3 is hardest
