### ISSUE TITLE
planting bomb

### ISSUE THREAD

**Issue by Riucelo** [ineedbots/pt6_bot_warfare#35]
Hello.
Firstly would like to express appreciation for Bot warfare. Love all of them. Excited for Cod2 bots too <3

T6 bots seems to work nice and are strong enough. I love S&D mod and I notice they come to objective, but can't plant or defuse the bomb. Same in Sabotage gamemode.
Is there any plans to add this functionality in near future? 

I have more questions and suggestions, but I don't think it is good idea to post all of it in here of T6 section. Is your email is the best way to contact you? Thank you for your time and effort

**Comment by ineedbots** [comment]
I cannot recreate your issue, they plant the bomb just fine for me; is it possible in your case that they were just picking up weapons that were near the bombsite?

![image](https://github.com/ineedbots/t6_bot_warfare/assets/751729/ed8e78bc-de94-4019-a409-a10f3e37f71c)

**Comment by Riucelo** [comment]
No. I had 2 situations. 
I just made 2v1 in Plaza. The bot went to objective just lays there and after some time it starts to walk around plant area and then it went lay down (looks like planting, but no planting) and repeating. Never planting

Another test was in different map Hydro 5v5 or 6v6. 3 bots stand at the plant area, but nobody plants even 1 minute passed.

I got the latest files and everything works well except planting the bomb. Any ideas?

**Comment by Riucelo** [comment]
i tried to spectate what they are doing. Its like they try to plant or defuse, BUT it is too short time. Lets say 5sec is needed to plant or defuse and they do it for around 2sec and then bot will cancel the action even everyone is dead.

**Comment by Riucelo** [comment]
yesterday i added custom names for bots and tried one more time and now its planting. i restarted the game and tried one more time and its planting the bomb. I don't think it is logical by adding names could let them plant? 
But anyway its working now. Thanks for you time. Now waiting so much for Cod2 bots :)
