### ISSUE TITLE
Broken AI logic

### ISSUE THREAD

**Issue by UnluckyKitty** [ineedbots/pt6_bot_warfare#43]
When you spawn bots on your server, regardless of the difficulty level, there is always a bot in your or the enemy team that ignores everyone. He performs his tasks, such as destroying scorestreaks or capturing flags, but when he sees the enemy he does not shoot at him. Is it possible to somehow fix this ?

**Comment by ineedbots** [comment]
this issue will be fixed in the next plutonium update

**Comment by UnluckyKitty** [comment]
Sounds good, thanks for the answer
