### ISSUE TITLE
Changes made in the "botwarfare" cfg file have no effect ingame

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/pt6_bot_warfare#5]
Example: I set "setDvar( "bots_loadout_rank", -1 );" to "setDvar( "bots_loadout_rank", 0 );" but when I check ingame it´s still saying "-1". Same with every other dvar (like the several difficulty settings). I downloaded your mod mainly to increase the bots difficulty as they´re too easy even on veteran. The folders "maps" and "scripts" are inside "storage/t6" so I must have installed it correctly

**Comment by ineedbots** [comment]
.cfg files are meant for dedicated server, not local games.

**Comment by LeRutY** [comment]
@ineedbots Well even when creating and playing on the own dedicated server the dvar values don´t change

**Comment by ineedbots** [comment]
try changing the dedicated.cfg file name to something else, it could be conflicting with the dedicated.cfg file found in your localappdata t6 storage folder

**Comment by hxj662630** [comment]
just wanna know how to compile file in scripts\mp(like compile botwarfare to botwarfare-compiled)

**Comment by ineedbots** [comment]
https://github.com/ineedbots/pt6_bot_warfare/tree/master/.vscode

the compiler .exe file, drag and drop the gsc source file onto the executable and it will generate the compiled gsc

**Comment by ineedbots** [comment]
or if you are using vscode, you can run this task to compile the current opened gsc file
![image](https://user-images.githubusercontent.com/751729/159761715-fed2f291-3a2e-446a-9c97-5cd53d63674e.png)

**Comment by hxj662630** [comment]
Thx, bro
