### ISSUE TITLE
How do i install this to my dedicated server?

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/pt6_bot_warfare#6]
I dropped the scripts folder into the storage/t6, then start the server. But after i start the server, it fails to load the scripts, and causes me to not be able to connect to the server, because without the scripts i can connect to my own server. Its the mod thats causing me to not connect to my server.

**Comment by ineedbots** [comment]
Stick the compiled gsc file inside of %localappdata%\plutonium\storage\t6\scripts\mp\ folder and run your dedicated server
