### ISSUE TITLE
Mispaced Thingy things Solwed

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/pt6_bot_warfare#7]
Hi! Please check your repo, i guess lots of files missing! @ineedbots

**Comment by Evan-Johnston** [comment]
Also wondering if this is the case. @ineedbots

**Comment by megvadulthangya** [comment]
100% its the case look at all outher existing botwarfare raw directory's...

**Comment by GaryTheNoTrashCougar** [comment]
Maybe because bots are already in the game? This mod still works, not exactly sure what tweaks it makes but you can still use DVARs in the console.

bots_loadout_prestige -2;bots_loadout_rank 0;bots_skill 3;bots_manage_fill 18

**Comment by megvadulthangya** [comment]
Does not work at all....

I have this cfg which works all of the Botwarfare version which exist.

Tryed add at the end to exec bots.cfg 
Dont work, commented out the exec bots.cfg
and pasted into the server.cfg
Does not work!

Copyed all the files in raw folder, does not work.

// *********************************************
// **** 		cod4x_bot Commented			****
// ****         Configuration file			****
// ****           By Rohambili				****
// *********************************************



set bots_main "1"					// Enable this mod.
set bots_main_GUIDs "YOURGUIDGOESHERE"				// A comma separated list of GUIDs of players who will be given host.
set bots_main_firstIsHost "0"		// The first player to connect will be given host.
set bots_main_waitForHostTime "5"	// How many seconds to wait for the host player to connect before adding bots to the match. 
set bots_main_menu "1"				// Enable the in-game menu for hosts.
set bots_main_debug "0"				// Enable the in-game waypoint editor.
set bots_main_kickBotsAtEnd "1"		//	Kick the bots at the end of a match.
set bots_manage_add "8"			// an integer amount of bots to add to the game, resets to 0 once the bots have been added. for example: 'bots_manage_add 10' will add 10 bots to the game.
set bots_manage_fill "8"			// an integer amount of players/bots (depends on bots_manage_fill_mode) to retain on the server, it will automatically add bots to fill player space.
									// for example: 'bots_manage_fill 10' will have the server retain 10 players in the server, if there are less than 10, it will add bots until that value is reached.
set bots_manage_fill_spec "0"		// a﻿ boolean valu﻿e (0 or 1), whether﻿ or not if the server should con﻿side﻿r players who are on the spectator team when filling player space.
set bots_manage_fill_mode "0"		// a value to indicate if the server should consider only bots or players and bots when filling player space.
									// 0 will consider both players and bots.
									// 1 will only consider bots.
set bots_manage_fill_kick "1"		// a boolean value (0 or 1), whether﻿ or not if the server should kick bots if the amount of players/bots (depends on bots_manage_fill_mode) exceeds the value of bots_manage_fill.
set bots_team "autoassign"			// a string, the value indicates what team the bots should join:
									// 'autoassign' will have bots balance the teams
									// 'allies' will have the bots join the allies team
									// 'axis' will have the bots join the axis team
									// 'custom' will have bots_team_amount bots on the axis team, the rest will be on the allies team
set bots_team_amount "0"			// an integer amount of bots to have on the axis team if bots_team is set to 'custom', the rest of the bots will be placed on the allies team.
									// for example: there are 5 bots on the server and 'bots_team_amount 3', then 3 bots will be placed on the axis team, the other 2 will be placed on the allies team.
set bots_team_force "1"				// a boolean value (0 or 1), whether or not if the server should enforce periodically the bot's team instead of just a single team when the bot is added to the game.﻿
									// for example: 'bots_team_force 1' and 'bots_team autoassign' and the teams become to far unbalanced, then the server will change a bot's team to make it balanced again.
set bots_team_mode "0"				// a value to indicate if the server should consider only bots or players and bots when counting players on the teams.
									// 0 will consider both players and bots.
									// 1 will only consider bots.
set bots_skill "8"					// value to indicate how difficult the bots should be.
									// 0 will be mixed difficultly
									// 1 will be the most easy
									// 2-6 will be in between most easy and most hard
									// 7 will be the most hard.
									// 8 will be custom.
set bots_skill_axis_hard "0"		// an integer amount of hard bots on the axis team. if bots_skill is 8 (custom)
set bots_skill_axis_med "1"			// an integer amount of medium bots on t﻿he axis te﻿a﻿m﻿﻿. if bots_skill is 8 (custom)
set bots_skill_allies_hard "0"		// an integer amou﻿nt of hard bots on the allies team. if bots_skill is 8 (custom)
set bots_skill_allies_med "1"		// an integer amount of medium bots on the allies team, if bots_skill is 8 (custom). The remaining bots on the team will become easy bots.﻿
									// for example: having 5 bots on the allies team, 'bots_skill_allies_hard 2' and 'bots_skill_allies_med 2' will have 2 hard bots, 2 medium bots, and 1 easy bot on the allies team.
set bots_loadout_reasonable "0"		// a boolean value (0 or 1), whether or not if the bots should filter out bad create a class selections (like no silenced miniuzi with overkill perk, etc)
set bots_loadout_allow_op "0"		// a boolean value (0 or 1), whether or not if the bots are allowed to use jug, marty and laststand.
set bots_loadout_rank "15"			// What rank to set the bots.
									// -1 - Average of all players in the match.
									// 0 - All random.
									// 1 or higher - Sets the bots' rank to this.

//Bot Loadout
set bots_loadout_tube "0" 						//Noob-tube Bots.
set bots_loadout "defualt"
set bots_loadout_killstreak "defualt"
set bots_loadout_nuke "0"
set bots_loadout_deathstreak "true"
set bots_loadout_lastStand "true"
set bots_loadout_riot "true"
set bots_loadout_sniper "true"
set bots_loadout_nade "true"
set bots_loadout_knife "true"
set bots_loadout_akimbo "true"

set bots_play_move "1"				// If the bots can move.
set bots_play_knife "1"				// If the bots can knife.
set bots_play_fire "1"				// If the bots can fire.
set bots_play_nade "1"				// If the bots can granade.
set bots_play_obj "1"				//	If the bots can play the objective.
set bots_play_camp "1"				// If the bots can camp.
set bots_play_jumpdrop "1"			// If the bots can jump/drop shot.
set bots_play_target_other "1"		// If the bots can target other entities other than players.
set bots_play_killstreak "1"		// If the bots can call in killstreaks.
set bots_play_ads "1"				// If the bots can aim down sights.
set bots_play_aim "1"				// If the bots can aim.
set bots_loadout_prestige "-1"		//
set bots_play_take_carepackages "1"	//



// ********************************************************************************************************************************************************************************************************************

**Comment by GaryTheNoTrashCougar** [comment]
For me this has worked:
Ensure you copy files in raw folder to `C:\Users\YourUserName\AppData\Local\Plutonium\storage\t6`.

**Method 1 - Client Only**
- Launch T6, go to ONLINE / RANKED / FIND MATCH option, then select a game mode you want to play.
- When in lobby searching for players, open the console & type `xpartygo` to launch a match. 
- Bot DVARs don't seem to work until a game is started, so wait until choosing a class then open console again & then type them in.  Probably best to type them up in notepad & separate them with semi colons so you can copy & paste into the console, also put command to spawn bots last otherwise settings won't apply until next game.

example:
`bots_loadout_prestige -2;bots_loadout_rank 0;bots_skill 3;bots_manage_fill 18`

**Method 2 - Dedicated Server**
- Follow guide to set up server if you haven't [here](https://plutonium.pw/docs/server/t6/setting-up-a-server/).
- Open `dedicated.cfg` located in `C:\Users\YourUserName\AppData\Local\Plutonium\storage\t6`.
- Enter DVARs you want to use somewhere in the config ensuring you set them.

example:
```
set bots_loadout_prestige -2
set bots_loadout_rank 0
set bots_skill 3
set bots_manage_fill 18
```
Hope this helps.

**Comment by megvadulthangya** [comment]
Thank you for your time. Im on dedicated did exactly what you wrote. Bots still not there.

**Comment by GaryTheNoTrashCougar** [comment]
Do you have full game (officially)?

**Comment by megvadulthangya** [comment]
Officially torrent...

[https://plutonium.pw/docs/server/t6/setting-up-a-server/](https://plutonium.pw/docs/server/t6/setting-up-a-server/)

I followed all the steps on this tutorial... also shrinked/slimmed the dedicated server

**Comment by GaryTheNoTrashCougar** [comment]
Do you use other DVARs? The config you pasted earlier definitely won't work.  Maybe link or paste your dedicated.cfg file so I can look at it

**Comment by megvadulthangya** [comment]
what i pasted is totally work on all botwarfare, just badly formated here. Whatch this: [https://et.sytes.net/%20cod4x_bot_warfare/cod4/cod4x_bot.cfg](https://et.sytes.net/cod4/%20cod4x_bot_warfare/cod4x_bot.cfg)

works in Plutonium T4, IW5, COD4x, IW4X

**Comment by GaryTheNoTrashCougar** [comment]
![Bot DVARs](https://user-images.githubusercontent.com/81429041/153926882-d250c559-5f3b-4645-affb-9e20fc22d468.png)
These are the only DVARs that work I believe.

**Comment by GaryTheNoTrashCougar** [comment]
So for example in the `dedicated.cfg` config I have placed the DVARs I want to use in the GENERAL CONFIGURATION section

example
```
//////////////////////////////////////////////////
// GENERAL CONFIGURATION                        //
//////////////////////////////////////////////////
g_password ""                                   // Password Protected Game Server (Use "password" to set it on the client before you connect,)
//sv_maxclients 18                              // How many players can join your server.
scr_showperksonspawn 1                          // Disable the perks on the right side on spawn.
//scr_deleteexplosivesonspawn 1                 // Delete Explosive while getting killed.
//sv_minPing 0                                  // Minimum ping needed to the server? (Terribly broken and inaccurate since ages!)
//sv_maxPing 400                                // Maximum ping allowed to the server? (Terribly broken and inaccurate since ages!)
//scr_disable_cac 1                             // Disable Custom Classes?
//scr_max_rank 0                                // Block every player with a level up this value
//scr_min_prestige 0                            // Block every player with a prestige below this value
//sv_restrictionList "restricted.cfg"           // Sets the file name for our restriction system.
//sv_enableItemRestriction 1                    // Enables our custom restriction system.
//g_customteamnames "allies,Team 1|axis,Team 2" // Set custom team names on scoreboard.
sv_allowAimAssist 1                             // Allow Aim Assist on gamepads. (0 = Will lock the option on gamepad controls menu.)
sv_allowDof 0                                   // Disallows the clients from having DoF to prevent a few DoF related glitches + gains a few frames. (0 = force off DoF on the clients, 1 = let the client decide)
demo_enabled 1                                  // Record matches as demo files? 1 = Enabled, 0 = Disabled (Very efficient <5MB per match for a full server)
sv_sayname "Console"                            // name server-side 'say' commands show up as
sv_patch_dsr50 true                             // Apply DSR-50 patches on this server? (true = stock game, false = pre-patch DSR-50)
set bots_loadout_prestige -2                    //
set bots_loadout_rank 0                         //
set bots_skill 3                                //
set bots_manage_fill 18                         //
//////////////////////////////////////////////////
```

**Comment by megvadulthangya** [comment]
I did this as well.

**Comment by GaryTheNoTrashCougar** [comment]
What OS are you on?

**Comment by megvadulthangya** [comment]
Debian10 with latest wine.
IW4X, Plutonium T4, IW5 Works fine. All have bots. [https://cod.g-shoots.hu](https://cod.g-shoots.hu)

**Comment by GaryTheNoTrashCougar** [comment]
Can you add bots to a game using method 1 in my comment earlier?

**Comment by megvadulthangya** [comment]
I think I know where is the problem.... Don't see the console in Linux..  And can't  make rcon commands, becouse my starting script... I belive the dedicated.cfg is bad placed... That goes to /Plutonium/storage/t6
Or game folder/main

**Comment by GaryTheNoTrashCougar** [comment]
I'm on Windows though but I have in storage\t6

**Comment by megvadulthangya** [comment]
Mine as well, ineedbots cfg is in main... I think I try to move there... And take look into log files... If it loads or not

**Comment by megvadulthangya** [comment]
> Can you add bots to a game using method 1 in my comment earlier?

Not gonna happened... This is a headless server. Only ssh :)

**Comment by GaryTheNoTrashCougar** [comment]
I have left all of those files untouched. The dedicated.cfg file came from the server set up guide. The only DVARs you will be able to use in t6 are the ones in the image I uploaded. This is due to the bots already being in the game. If you are using any other DVARs it could be causing the problem

**Comment by GaryTheNoTrashCougar** [comment]
> > Can you add bots to a game using method 1 in my comment earlier?
> 
> Not gonna happened... This is a headless server. Only ssh :) 

Ok, thought it might be a way of determining whether the mod is actually working. What about in the console window? Are the scripts loading or throwing up errors?

**Comment by megvadulthangya** [comment]
almost nothing in logfiles...
BTW ingame 
rcon login myrconpassword
then 
rcon status
Gives nothing at all... 

rcon map_rotate is works.

rcon bots_main 1
Did Nothing
rcon bots_manage_fill 8 did nothing

BTW 
I using the config from plutonium tutorial... and your DVARS

set bots_loadout_prestige -2                    //
set bots_loadout_rank 0                         //
set bots_skill 3                                //
set bots_manage_fill 18

**Comment by GaryTheNoTrashCougar** [comment]
I would say mod is not working then. I know there are issues with Plutonium on Linux. Maybe there is another way to install the mod? Wonder if the mods folder method works in BO2.

**Comment by megvadulthangya** [comment]
tomorow try to make iwd file and give a try... Thank you for your time!

**Comment by megvadulthangya** [comment]
created iwd from files/folders in raw folder placed into storage/t6/mods/bots
Then edited the startup script +set fs_game mods/bots
did nothing dont have bots.

**Comment by GaryTheNoTrashCougar** [comment]
Only other thing to try maybe is putting mods in server.  Anything is worth a try at this point.  Where you copied your server game files put contents of raw folder in "data" folder inside "t6r" folder in root directory.
So for example `C:\Program Files\Games\Plutonium (Server)\t6r\data`

**Comment by megvadulthangya** [comment]
> Only other thing to try maybe is putting mods in server. Anything is worth a try at this point. Where you copied your server game files put contents of raw folder in "data" folder inside "t6r" folder in root directory. So for example `C:\Program Files\Games\Plutonium (Server)\t6r\data`

This way need to remove the +set fs_game mods/bots from starting script...
in this example t6r 

Folder is contains the 
redist
and zone 
dircetory

and the starting scripts...?

IF Yes, this way does not work either.

**Comment by GaryTheNoTrashCougar** [comment]
Have you got any other mods working?

**Comment by GaryTheNoTrashCougar** [comment]
As bots are already in the game you could just tweak them yourself using [DVARs](https://gmzorz.com/bo2dvars.html#dvars).
There are some ai & bot tags.

**Comment by megvadulthangya** [comment]
I dont spend time with BO2. Dont even know there is mods exist for this puppy, i just see some noobish wepon skin "mods" as i remember...

**Comment by megvadulthangya** [comment]
I tryed in VMWARE Windows 11 running a dedicated server... With the shrinked version of server files Guess what? Nothing...
And lastly i tryed with my desktop... With the full game... Can you guess it?
[Yup](https://youtu.be/FzXLJ-p9qzo)! Just watch it

**Comment by GaryTheNoTrashCougar** [comment]
OK, copy contents of the raw folder, not the folder itself.

**Comment by megvadulthangya** [comment]
O.o That was hard ... Its working on desktop Thnx!

xcopy pt6_bot_warfare\raw\maps raw\maps\ /Y /I /E /H /C
xcopy pt6_bot_warfare\raw\scripts raw\scripts\ /Y /I /E /H /C
xcopy pt6_bot_warfare\main main\ /Y /I /E /H /C
xcopy pt6_bot_warfare\raw\bots.txt raw\ /Y /I /H /C


That is not meaning copy from raw to raw folder?

**Comment by GaryTheNoTrashCougar** [comment]
![image](https://user-images.githubusercontent.com/81429041/154372961-9f0679bf-90e7-4551-aec0-2a86003a3e5d.png)
This is how my AppData\Local\Plutonium\storage\t6 folder looks.

**Comment by megvadulthangya** [comment]
Is it possible to rename the bots? Placing into this folder (like on your screenshoot) the bots.txt  does not rename the 3arc thingy thing...

**Comment by GaryTheNoTrashCougar** [comment]
No you can't

**Comment by ineedbots** [comment]
https://github.com/fedddddd/t6-gsc-utils
Has the ability to include a bots.json for bot names.

**Comment by ineedbots** [comment]
NOTE: this is intended to be a BOT MANAGER for PLUTONIUM T6 DEDICATED SERVERS.

Black ops 2 already has bots that play objectives, and everything...
