### ISSUE TITLE
Question about the bots

### ISSUE THREAD

**Issue by FearRizzy** [ineedbots/pt6_bot_warfare#8]
When changing difficulties i noticed in the scripts it had a bunch of options such as mindeathtime or what not for the different difficulties. Do I need to enter all those according values everytime or is that just showing me the difference between the difficulties? Also is there a way to play mixed bots like some hard regular and recruit all on a team?

**Comment by ineedbots** [comment]
just use the `bots_skill` dvar to change their difficulty

**Comment by LeRutY** [comment]
> just use the `bots_skill` dvar to change their difficulty

So that means the dvars can´t be actually modified but only seen? Man that sucks, BO2 bots are so bad and boring to play against
